### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by marcelofabri** [soffes/getcoinsapp.com#1]
What's the license for this repository?

**Comment by soffes** [comment]
I intentionally didn't add one because I didn't want people straight copying it. Maybe I'll add one though. I'll think on it.

**Comment by marcelofabri** [comment]
Thanks for the quick response! One option that you could think about is selling it as a template.

**Comment by soffes** [comment]
Ya thought about cleaning it up and doing that. Thanks for the encouragement!

Closing for now.
